import js from '@eslint/js';
import prettier from 'eslint-config-prettier/flat';
import reactHooks from 'eslint-plugin-react-hooks';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
	{
		ignores: [
			'**/node_modules/',
			'**/.svelte-kit/',
			'**/.mastra/',
			'**/build/',
			'**/dist/',
			// Generated test artefacts.
			'**/coverage/',
			'**/playwright-report/',
			'**/test-results/',
			'apps/web/static/',
			// Generated by the TanStack Router plugin from the files in src/routes.
			'apps/web-react/src/routeTree.gen.ts',
			// Vendored agent skills — third-party scripts, not this project's code.
			'.agents/'
		]
	},

	js.configs.recommended,
	tseslint.configs.strictTypeChecked,
	tseslint.configs.stylisticTypeChecked,
	svelte.configs.recommended,

	{
		languageOptions: {
			globals: { ...globals.node, ...globals.browser },
			parserOptions: {
				// Resolves each file against the nearest tsconfig.json, which is what
				// makes type-aware linting work across both workspaces at once.
				projectService: true,
				tsconfigRootDir: import.meta.dirname,
				extraFileExtensions: ['.svelte']
			}
		}
	},

	{
		// Svelte files are parsed by svelte-eslint-parser, which delegates the
		// <script> blocks to the typescript-eslint parser for type information.
		// Scoped to apps/web: it is the only Svelte workspace, and it is deleted in
		// house-elf-shi.16 along with these two blocks.
		files: ['apps/web/**/*.svelte', 'apps/web/**/*.svelte.ts', 'apps/web/**/*.svelte.js'],
		languageOptions: {
			parserOptions: { parser: tseslint.parser }
		}
	},

	{
		// The React app. The flat-config entry point is nested under `configs.flat` —
		// the top-level `configs['recommended-latest']` is still the eslintrc shape
		// (`plugins` as an array) and ESLint 10 rejects it outright.
		//
		// v7 has no single `react-compiler` rule: the compiler's diagnostics ship as
		// individual rules (purity, immutability, refs, set-state-in-render, …), all
		// already at error in this config. A component tripping one is a component the
		// compiler will bail out of, which silently costs it memoisation — so the
		// defaults are what we want and nothing is re-stated here.
		files: ['apps/web-react/**/*.{ts,tsx}'],
		extends: [reactHooks.configs.flat['recommended-latest']]
	},

	{
		// Config files at the repo root are not part of any tsconfig, so the project
		// service cannot type them. Lint them syntactically only.
		files: ['**/*.js'],
		extends: [tseslint.configs.disableTypeChecked],
		languageOptions: {
			parserOptions: { projectService: false }
		}
	},

	// Must come last: turns off every rule Prettier owns.
	prettier,
	svelte.configs.prettier
);
